"""Esquema y acceso a la base de datos (SQLite en el escritorio, PostgreSQL en el servidor).

El esquema se escribe una sola vez, en dialecto PostgreSQL; `a_sqlite()` lo traduce para la
app de escritorio, que tiene una sola empresa y no necesita las políticas RLS ni las claves
foráneas compuestas que aíslan empresas en el servidor.

La conexión la da `core.conexion`, que conserva la forma de uso de SQLite (`?`, `lastrowid`,
`date('now')`…) para que el resto de la app no cambie. Aquí vive el esquema y las funciones
de datos de cada módulo.

Convenciones que se conservan de la versión SQLite:
  · Las fechas son TEXTO ISO (`YYYY-MM-DD`, `YYYY-MM-DD HH:MM:SS`), no DATE/TIMESTAMP.
  · Los booleanos son INTEGER 0/1.
"""
from datetime import date
from pathlib import Path

from werkzeug.security import generate_password_hash as _generar_hash
import hashlib
import secrets


def generate_password_hash(password):
    """Hash de contraseña. scrypt (lo que usa Werkzeug por defecto) no existe en el Python de
    macOS, que va con LibreSSL: ahí crear o cambiar una contraseña fallaba. Se usa scrypt si está
    y, si no, PBKDF2-SHA256, que Werkzeug sigue verificando sin problema."""
    metodo = "scrypt" if hasattr(hashlib, "scrypt") else "pbkdf2:sha256:600000"
    return _generar_hash(password, method=metodo)

from core import conexion as core_conexion
from core import modelos as core_modelos
from core import aeronaves as core_aeronaves
from core import flota as core_flota

RAIZ = Path(__file__).resolve().parent.parent

_FECHA = "TEXT DEFAULT to_char(CURRENT_DATE, 'YYYY-MM-DD')"
_AHORA = "TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')"
_ID = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

ESQUEMA = f"""
-- SQLite redondea REAL con ROUND(x, n); en PostgreSQL eso sólo existe para NUMERIC.
CREATE OR REPLACE FUNCTION round(double precision, integer) RETURNS numeric
  AS 'SELECT round($1::numeric, $2)' LANGUAGE sql IMMUTABLE STRICT;

-- ===== Multi-empresa =====
-- Cada fila de datos pertenece a una empresa (`empresa_id`). La app fija la empresa de la
-- sesión en la conexión (`SET app.empresa_id`) y PostgreSQL hace el resto:
--   · empresa_actual() rellena empresa_id en cada INSERT (DEFAULT),
--   · las políticas de Row-Level Security filtran TODO SELECT/UPDATE/DELETE por esa empresa.
-- Así ninguna consulta puede ver ni tocar datos de otra empresa aunque se olvide el WHERE.
-- Las tareas de administración (migraciones, siembra) usan app.empresa_id = '*' (sin filtro).
CREATE OR REPLACE FUNCTION empresa_actual() RETURNS integer AS $$
  SELECT NULLIF(NULLIF(current_setting('app.empresa_id', true), '*'), '')::integer
$$ LANGUAGE sql STABLE;

CREATE TABLE IF NOT EXISTS empresas(
  id {_ID},
  nombre TEXT NOT NULL,
  nit TEXT,
  contacto TEXT,
  email TEXT,
  telefono TEXT,
  activa INTEGER NOT NULL DEFAULT 1,
  nota TEXT,
  creado {_AHORA}
);

-- Configuración y datos sueltos de cada empresa (SMTP, posiciones de los números en las
-- láminas, bitácoras ya importadas…).
CREATE TABLE IF NOT EXISTS meta(
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  clave TEXT NOT NULL,
  valor TEXT,
  PRIMARY KEY(empresa_id, clave)
);

-- Cuentas de acceso a la app (no confundir con `personal`, que es el directorio de contactos).
-- `rol`: admin (todo), tecnico (mantenimiento y órdenes de trabajo), piloto (operaciones y
-- órdenes de servicio). Ver PERMISOS en app.py.
-- `rol`: superadmin (gestiona empresas; puede entrar a cualquiera), admin (todo dentro de su
-- empresa), tecnico, piloto. El nombre de usuario es único en todo el sistema.
CREATE TABLE IF NOT EXISTS usuarios(
  id {_ID},
  empresa_id INTEGER REFERENCES empresas(id) ON DELETE CASCADE,
  usuario TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  nombre TEXT,
  email TEXT,
  rol TEXT NOT NULL DEFAULT 'admin',
  activo INTEGER NOT NULL DEFAULT 1,
  ultimo_acceso TEXT,
  creado {_AHORA}
);

-- Intentos de entrada fallidos, para frenar la fuerza bruta (se limpia sola).
CREATE TABLE IF NOT EXISTS login_intentos(
  usuario TEXT,
  ip TEXT,
  creado TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_login_intentos ON login_intentos(usuario, ip, creado);

CREATE TABLE IF NOT EXISTS equipos(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  modelo TEXT NOT NULL DEFAULT 'T50',
  numero_serie TEXT,
  fecha_alta {_FECHA},
  estado TEXT DEFAULT 'activo',
  horas_totales DOUBLE PRECISION DEFAULT 0,
  nota TEXT,
  creado {_AHORA},
  UNIQUE(empresa_id, id)
);

CREATE TABLE IF NOT EXISTS registros(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  categoria TEXT DEFAULT 'General',
  estado TEXT DEFAULT 'pendiente',
  vence TEXT,
  nota TEXT,
  equipo_id INTEGER,
  creado {_AHORA},
  actualizado {_AHORA},
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE SET NULL (equipo_id)
);

-- Piezas con vida útil, las que generan alertas de mantenimiento. Una misma clave («motor»)
-- existe en varios modelos con vida útil distinta, así que lo único de cada fila es el par
-- (modelo, clave). `vida_util_meses` está porque no todos los fabricantes publican la vida en
-- horas: del T100, DJI sólo da plazos de calendario. Si una pieza tiene los dos plazos, la
-- alerta salta con el que se cumpla primero.
CREATE TABLE IF NOT EXISTS catalogo_piezas(
  id {_ID},
  modelo TEXT NOT NULL DEFAULT 'T50',
  clave TEXT NOT NULL,
  modulo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  vida_util_horas DOUBLE PRECISION NOT NULL DEFAULT 0,
  vida_util_meses DOUBLE PRECISION NOT NULL DEFAULT 0,
  nota TEXT,
  mesh TEXT,
  zona TEXT,
  UNIQUE(modelo, clave)
);

-- Despiece completo de cada modelo tal y como viene en los diagramas oficiales de DJI: cada
-- pieza con su código, su módulo y su número en la lámina. A diferencia de catalogo_piezas,
-- estas NO llevan vida útil ni horas: son el recambio que se pide, no lo que se cronometra.
CREATE TABLE IF NOT EXISTS catalogo_despiece(
  id {_ID},
  modelo TEXT NOT NULL DEFAULT 'T50',
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  nombre_en TEXT,
  nombre_zh TEXT,
  modulo_clave TEXT NOT NULL,
  modulo TEXT NOT NULL,
  n INTEGER,
  auxiliar INTEGER DEFAULT 0,
  zona TEXT,
  UNIQUE(modelo, modulo_clave, n, codigo)
);

CREATE TABLE IF NOT EXISTS componentes(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  equipo_id INTEGER NOT NULL,
  pieza_id INTEGER NOT NULL REFERENCES catalogo_piezas(id) ON DELETE CASCADE,
  horas_uso DOUBLE PRECISION DEFAULT 0,
  fecha_instalado {_FECHA},
  fecha_ultimo_cambio TEXT,
  UNIQUE(equipo_id, pieza_id),
  UNIQUE(empresa_id, id),
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS operaciones(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  equipo_id INTEGER NOT NULL,
  fecha {_FECHA},
  horas_vuelo DOUBLE PRECISION NOT NULL DEFAULT 0,
  tiempo_total DOUBLE PRECISION,
  despegues INTEGER,
  hectareas DOUBLE PRECISION,
  producto TEXT,
  litros DOUBLE PRECISION,
  piloto TEXT,
  cliente TEXT,
  zona TEXT,
  lote TEXT,
  nota TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mantenimientos(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  equipo_id INTEGER NOT NULL,
  componente_id INTEGER,
  tipo TEXT DEFAULT 'preventivo',
  fecha {_FECHA},
  horas_al_momento DOUBLE PRECISION,
  descripcion TEXT,
  costo DOUBLE PRECISION,
  realizado_por TEXT,
  -- Bitácora de reparaciones: qué pieza se tocó y con cuántas horas encima. Se guarda el
  -- pieza_id además del componente_id porque el componente se puede borrar con el equipo, y
  -- horas_pieza porque el cambio pone el contador a cero y si no se pierde el dato.
  pieza_id INTEGER,
  horas_pieza DOUBLE PRECISION,
  motivo TEXT DEFAULT 'desgaste',
  codigo_pieza TEXT,
  nombre_pieza TEXT,
  orden_id INTEGER,
  orden_codigo TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY(empresa_id, componente_id) REFERENCES componentes(empresa_id, id) ON DELETE SET NULL (componente_id)
);

-- Directorio de contactos: personal propio y gente de fuera (clientes, proveedores, servicio
-- técnico). `rol` dice qué es para la app (a un piloto se le asignan órdenes de servicio, a un
-- técnico órdenes de trabajo) y `cargo` es su puesto tal y como se escribe en una firma.
CREATE TABLE IF NOT EXISTS personal(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  rol TEXT DEFAULT 'tecnico',
  cargo TEXT,
  empresa TEXT,
  documento TEXT,
  email TEXT,
  telefono TEXT,
  telefono2 TEXT,
  direccion TEXT,
  ciudad TEXT,
  licencia TEXT,
  licencia_vence TEXT,
  ingreso TEXT,
  activo INTEGER DEFAULT 1,
  nota TEXT,
  creado {_AHORA},
  actualizado {_AHORA}
);

CREATE TABLE IF NOT EXISTS ordenes_trabajo(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  codigo TEXT NOT NULL,
  equipo_id INTEGER NOT NULL,
  titulo TEXT NOT NULL,
  tipo TEXT DEFAULT 'preventivo',
  prioridad TEXT DEFAULT 'normal',
  estado TEXT DEFAULT 'borrador',
  asignado_a TEXT,
  asignado_email TEXT,
  fecha_programada TEXT,
  hora_programada TEXT,
  lugar TEXT,
  horas_equipo DOUBLE PRECISION,
  observaciones TEXT,
  creado_por TEXT,
  enviado_en TEXT,
  cerrado_en TEXT,
  creado {_AHORA},
  actualizado {_AHORA},
  UNIQUE(empresa_id, codigo),
  UNIQUE(empresa_id, id),
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ot_tareas(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  orden_id INTEGER NOT NULL,
  descripcion TEXT NOT NULL,
  origen TEXT DEFAULT 'cronograma',
  pieza_clave TEXT,
  componente_id INTEGER,
  nivel TEXT,
  estado TEXT DEFAULT 'pendiente',
  nota TEXT,
  motivo TEXT,
  codigo_pieza TEXT,
  nombre_pieza TEXT,
  orden_n INTEGER DEFAULT 0,
  FOREIGN KEY(empresa_id, orden_id) REFERENCES ordenes_trabajo(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY(empresa_id, componente_id) REFERENCES componentes(empresa_id, id) ON DELETE SET NULL (componente_id)
);

CREATE TABLE IF NOT EXISTS ordenes_servicio(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  codigo TEXT NOT NULL,
  piloto TEXT,
  piloto_email TEXT,
  cliente TEXT,
  finca TEXT,
  zona TEXT,
  productos TEXT,
  fecha TEXT,
  hora TEXT,
  equipo_id INTEGER,
  hectareas DOUBLE PRECISION,
  dosis TEXT,
  observaciones TEXT,
  estado TEXT DEFAULT 'programada',
  creado_por TEXT,
  enviado_en TEXT,
  finalizado_en TEXT,
  creado {_AHORA},
  actualizado {_AHORA},
  UNIQUE(empresa_id, codigo),
  UNIQUE(empresa_id, id),
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE SET NULL (equipo_id)
);

CREATE TABLE IF NOT EXISTS os_productos(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  orden_id INTEGER NOT NULL,
  nombre TEXT NOT NULL,
  dosis TEXT,
  cantidad DOUBLE PRECISION,
  unidad TEXT DEFAULT 'L',
  nota TEXT,
  orden_n INTEGER DEFAULT 0,
  FOREIGN KEY(empresa_id, orden_id) REFERENCES ordenes_servicio(empresa_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS os_eventos(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  orden_id INTEGER NOT NULL,
  estado TEXT NOT NULL,
  nota TEXT,
  usuario TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, orden_id) REFERENCES ordenes_servicio(empresa_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS correo_cola(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  para TEXT NOT NULL,
  asunto TEXT NOT NULL,
  cuerpo TEXT NOT NULL,
  referencia TEXT,
  estado TEXT DEFAULT 'pendiente',
  error TEXT,
  intentos INTEGER DEFAULT 0,
  creado {_AHORA},
  enviado TEXT
);

CREATE INDEX IF NOT EXISTS ix_op_equipo_fecha ON operaciones(equipo_id, fecha);
CREATE INDEX IF NOT EXISTS ix_mant_equipo_fecha ON mantenimientos(equipo_id, fecha);
CREATE INDEX IF NOT EXISTS ix_ot_estado ON ordenes_trabajo(estado, fecha_programada);
CREATE INDEX IF NOT EXISTS ix_os_estado ON ordenes_servicio(estado, fecha);
CREATE INDEX IF NOT EXISTS ix_op_fecha ON operaciones(fecha);
CREATE INDEX IF NOT EXISTS ix_op_piloto ON operaciones(piloto);
CREATE INDEX IF NOT EXISTS ix_op_cliente ON operaciones(cliente);
CREATE INDEX IF NOT EXISTS ix_ot_asignado ON ordenes_trabajo(asignado_a);
CREATE INDEX IF NOT EXISTS ix_os_piloto ON ordenes_servicio(piloto);
CREATE INDEX IF NOT EXISTS ix_comp_equipo ON componentes(equipo_id);
CREATE INDEX IF NOT EXISTS ix_mant_fecha ON mantenimientos(fecha);
CREATE INDEX IF NOT EXISTS ix_usuarios_empresa ON usuarios(empresa_id);
"""

# ===== Flota mixta: drones y aviones (ver core/flota.py) =====
COLUMNAS_FLOTA = {
    "equipos": {"tipo_activo": "TEXT NOT NULL DEFAULT 'dron'", "matricula": "TEXT", "anio": "INTEGER",
                "base": "TEXT", "fabricante": "TEXT", "fecha_baja": "TEXT", "motivo_baja": "TEXT"},
    "catalogo_piezas": {"empresa_id": "INTEGER DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE",
                        "tipo_item": "TEXT NOT NULL DEFAULT 'pieza'",
                        "contador_base": "TEXT NOT NULL DEFAULT 'horas_vuelo'",
                        "contador_ciclos": "TEXT", "limite_ciclos": "DOUBLE PRECISION NOT NULL DEFAULT 0",
                        "tolerancia": "DOUBLE PRECISION NOT NULL DEFAULT 0",
                        "serializada": "INTEGER NOT NULL DEFAULT 0", "referencia": "INTEGER NOT NULL DEFAULT 0",
                        "precio": "DOUBLE PRECISION"},
    # uso_inicial NULL = componente de antes de los contadores: conciliar() lo rellena una vez.
    "componentes": {"uso_inicial": "DOUBLE PRECISION", "ciclos_uso": "DOUBLE PRECISION DEFAULT 0",
                    "ciclos_inicial": "DOUBLE PRECISION DEFAULT 0", "pieza_serie_id": "INTEGER"},
    "operaciones": {"hobbs_ini": "DOUBLE PRECISION", "hobbs_fin": "DOUBLE PRECISION",
                    "tach_ini": "DOUBLE PRECISION", "tach_fin": "DOUBLE PRECISION",
                    "aterrizajes": "INTEGER", "arranques": "INTEGER", "combustible_gal": "DOUBLE PRECISION",
                    "pista": "TEXT", "tiempo_traslado": "DOUBLE PRECISION", "ha_programadas": "DOUBLE PRECISION",
                    "temperatura": "DOUBLE PRECISION", "humedad": "DOUBLE PRECISION",
                    "viento": "DOUBLE PRECISION", "velocidad": "DOUBLE PRECISION",
                    "altura": "DOUBLE PRECISION", "dosis_objetivo": "DOUBLE PRECISION",
                    # Libro de a bordo (RAC 91.1410) y libro de vuelo del UA (RAC 100.005).
                    "hora_salida": "TEXT", "hora_llegada": "TEXT", "origen": "TEXT", "destino": "TEXT",
                    "proposito": "TEXT", "personal_id": "INTEGER"},
    "mantenimientos": {"costo_repuesto": "DOUBLE PRECISION", "costo_mano_obra": "DOUBLE PRECISION",
                       "firmado_por": "TEXT", "licencia_firma": "TEXT",
                       # Para poder deshacer el cambio de pieza si el registro se borra.
                       "fecha_cambio_anterior": "TEXT", "uso_inicial_anterior": "DOUBLE PRECISION",
                       "ciclos_inicial_anterior": "DOUBLE PRECISION", "pieza_serie_id": "INTEGER"},
    "ot_tareas": {"costo_repuesto": "DOUBLE PRECISION", "costo_mano_obra": "DOUBLE PRECISION",
                  "horas_mano_obra": "DOUBLE PRECISION"},
    "ordenes_trabajo": {"firmado_por": "TEXT", "licencia_firma": "TEXT",
                        # Pasos que pide la aviación tripulada (RAC 145 / 43): aprobación del jefe
                        # técnico antes de empezar, inspección independiente (segunda firma), trabajo
                        # diferido con plazo y trabajo contratado a un taller externo.
                        "aprobado_por": "TEXT", "aprobado_en": "TEXT",
                        "inspector": "TEXT", "inspector_licencia": "TEXT",
                        "diferida_hasta": "TEXT", "diferida_motivo": "TEXT",
                        "taller_externo": "TEXT", "taller_certificado": "TEXT",
                        "horas_hombre": "DOUBLE PRECISION"},
    "personal": {"licencia_tipo": "TEXT", "habilitaciones": "TEXT"},
    # Orden de servicio: lo que el piloto pidió saber antes de salir (encuesta de validación).
    "ordenes_servicio": {"condiciones_tiempo": "TEXT", "zonas_evitar": "TEXT", "mapa_url": "TEXT",
                         "mapa_archivo": "TEXT"},
    "usuarios": {"tema": "TEXT",
                 # 1 = al entrar, la app obliga a cambiar la contraseña antes de nada.
                 "debe_cambiar_password": "INTEGER NOT NULL DEFAULT 0"},
}

# Columnas nuevas de tablas que crea ESQUEMA_FLOTA: se añaden DESPUÉS de crearlo (en una base
# nueva la tabla aún no existe cuando se aplican las de COLUMNAS_FLOTA).
COLUMNAS_POSTERIORES = {
    # Cómo cobra el cliente: 'ha' (valor_ha es por hectárea) u 'hora' (valor_ha es por hora de vuelo).
    "tarifas": {"unidad": "TEXT NOT NULL DEFAULT 'ha'"},
    # Producto de la empresa o del cliente: el inventario y el costo sólo cuentan lo propio; lo del
    # cliente se registra para la trazabilidad de la aplicación (RAC 137.71).
    "bodega_items": {"propietario": "TEXT NOT NULL DEFAULT 'empresa'", "cliente": "TEXT"},
}

ESQUEMA_FLOTA = f"""
CREATE TABLE IF NOT EXISTS modelos_activo(
  id {_ID},
  empresa_id INTEGER DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  clave TEXT NOT NULL UNIQUE,
  tipo_activo TEXT NOT NULL DEFAULT 'dron',
  fabricante TEXT,
  nombre TEXT NOT NULL,
  contadores TEXT NOT NULL DEFAULT 'horas_vuelo,despegues',
  descripcion TEXT,
  plantilla TEXT,
  es_plantilla INTEGER NOT NULL DEFAULT 0,
  activo INTEGER NOT NULL DEFAULT 1,
  creado {_AHORA}
);

-- Lectura inicial de cada contador del activo. Lectura actual = inicial + Σ operaciones.
CREATE TABLE IF NOT EXISTS contadores_equipo(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  equipo_id INTEGER NOT NULL,
  contador TEXT NOT NULL,
  valor_inicial DOUBLE PRECISION NOT NULL DEFAULT 0,
  creado {_AHORA},
  UNIQUE(equipo_id, contador),
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);

-- Piezas con número de serie que viajan con su historial: motor, hélice, magnetos, baterías.
-- tso_inicial: uso desde overhaul (o desde nueva) cuando se registró; uso_acumulado: al último
-- desmontaje. Mientras está montada, su uso lo lleva el componente.
CREATE TABLE IF NOT EXISTS piezas_serie(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'pieza',
  pieza_clave TEXT,
  serial TEXT NOT NULL,
  descripcion TEXT,
  uso_acumulado DOUBLE PRECISION DEFAULT 0,
  tso_inicial DOUBLE PRECISION DEFAULT 0,
  tsn_inicial DOUBLE PRECISION,
  ciclos_acumulados DOUBLE PRECISION DEFAULT 0,
  vida_ciclos DOUBLE PRECISION,
  estado TEXT NOT NULL DEFAULT 'bodega',
  equipo_id INTEGER,
  componente_id INTEGER,
  fecha_asignada TEXT,
  fecha_compra TEXT,
  precio DOUBLE PRECISION,
  nota TEXT,
  creado {_AHORA},
  UNIQUE(empresa_id, id),
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE SET NULL (equipo_id)
);

CREATE TABLE IF NOT EXISTS instalaciones(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  pieza_serie_id INTEGER NOT NULL,
  equipo_id INTEGER NOT NULL,
  componente_id INTEGER,
  desde TEXT,
  hasta TEXT,
  uso_al_montar DOUBLE PRECISION,
  uso_al_desmontar DOUBLE PRECISION,
  motivo TEXT,
  usuario TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, pieza_serie_id) REFERENCES piezas_serie(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);

-- Directivas de aeronavegabilidad (AD) y boletines de servicio (SB) por modelo.
CREATE TABLE IF NOT EXISTS directivas(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  modelo TEXT,
  numero TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'AD',
  titulo TEXT NOT NULL,
  descripcion TEXT,
  aplica_a TEXT,
  recurrente INTEGER NOT NULL DEFAULT 0,
  intervalo_valor DOUBLE PRECISION,
  intervalo_contador TEXT,
  intervalo_dias INTEGER,
  limite_fecha TEXT,
  limite_valor DOUBLE PRECISION,
  fuente TEXT,
  url TEXT,
  creado {_AHORA},
  UNIQUE(empresa_id, id)
);

CREATE TABLE IF NOT EXISTS cumplimiento_directiva(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  directiva_id INTEGER NOT NULL,
  equipo_id INTEGER NOT NULL,
  estado TEXT NOT NULL DEFAULT 'cumplida',
  fecha TEXT,
  valor_contador DOUBLE PRECISION,
  firmado_por TEXT,
  licencia TEXT,
  nota TEXT,
  orden_id INTEGER,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, directiva_id) REFERENCES directivas(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS documentos(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  equipo_id INTEGER,
  personal_id INTEGER,
  tipo TEXT NOT NULL,
  numero TEXT,
  emitido TEXT,
  vence TEXT,
  nota TEXT,
  archivo TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tarifas(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  cliente TEXT NOT NULL,
  tipo_activo TEXT NOT NULL DEFAULT 'todos',
  valor_ha DOUBLE PRECISION NOT NULL,
  desde TEXT,
  nota TEXT,
  creado {_AHORA}
);

CREATE TABLE IF NOT EXISTS auditoria(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  tabla TEXT NOT NULL,
  fila_id INTEGER,
  campo TEXT,
  antes TEXT,
  despues TEXT,
  usuario TEXT,
  motivo TEXT,
  creado {_AHORA}
);

-- Chequeo pre-vuelo del piloto: lista de puntos con resultado, nota y foto opcional.
CREATE TABLE IF NOT EXISTS checklists(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  equipo_id INTEGER NOT NULL,
  fecha TEXT,
  piloto TEXT,
  resultado TEXT NOT NULL DEFAULT 'apto',
  items TEXT NOT NULL,
  nota TEXT,
  orden_id INTEGER,
  usuario TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);

-- Foto diaria del estado de cada activo: con ella se mide la disponibilidad histórica. Se
-- actualiza sola durante el día (la última foto del día queda) y con `manage.py fotos-estado`.
CREATE TABLE IF NOT EXISTS estado_diario(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  equipo_id INTEGER NOT NULL,
  fecha TEXT NOT NULL,
  estado TEXT NOT NULL,
  estado_equipo TEXT,
  motivos TEXT,
  actualizado {_AHORA},
  UNIQUE(equipo_id, fecha),
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_cumpl_dir ON cumplimiento_directiva(directiva_id, equipo_id);
CREATE INDEX IF NOT EXISTS ix_doc_vence ON documentos(vence);
CREATE INDEX IF NOT EXISTS ix_serie_equipo ON piezas_serie(equipo_id);
CREATE INDEX IF NOT EXISTS ix_check_equipo ON checklists(equipo_id, fecha);

-- ===== Combustible (core/combustible.py) =====
-- Depósitos propios de la empresa: cisterna en la pista, carrotanque, bidones del generador.
-- El nivel no se guarda: se reconstruye con nivel_inicial + compras − tanqueos − mermas ± medición.
CREATE TABLE IF NOT EXISTS combustible_depositos(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  combustible TEXT NOT NULL DEFAULT 'avgas_100ll',
  capacidad_gal DOUBLE PRECISION NOT NULL DEFAULT 0,
  nivel_inicial_gal DOUBLE PRECISION NOT NULL DEFAULT 0,
  fecha_inicial TEXT,
  ubicacion TEXT,
  activo INTEGER NOT NULL DEFAULT 1,
  nota TEXT,
  creado {_AHORA},
  UNIQUE(empresa_id, id)
);

-- Cada movimiento de combustible: compra (entra al depósito), tanqueo (sale a un activo, del
-- depósito o comprado en el aeródromo), merma (drenaje, muestra, derrame) y medición (varillaje:
-- `nivel_medido`; `galones` guarda el descuadre frente al nivel calculado).
CREATE TABLE IF NOT EXISTS combustible_movimientos(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'tanqueo',
  fecha {_FECHA},
  hora TEXT,
  deposito_id INTEGER,
  equipo_id INTEGER,
  destino TEXT,
  combustible TEXT NOT NULL DEFAULT 'avgas_100ll',
  galones DOUBLE PRECISION NOT NULL DEFAULT 0,
  precio_gal DOUBLE PRECISION,
  total DOUBLE PRECISION,
  proveedor TEXT,
  documento TEXT,
  lleno INTEGER NOT NULL DEFAULT 0,
  lectura DOUBLE PRECISION,
  nivel_medido DOUBLE PRECISION,
  chequeo TEXT,
  responsable TEXT,
  nota TEXT,
  archivo TEXT,
  usuario TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, deposito_id) REFERENCES combustible_depositos(empresa_id, id) ON DELETE SET NULL (deposito_id),
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE SET NULL (equipo_id)
);
CREATE INDEX IF NOT EXISTS ix_comb_fecha ON combustible_movimientos(fecha);
CREATE INDEX IF NOT EXISTS ix_comb_equipo ON combustible_movimientos(equipo_id, fecha);

-- ===== Bodega (core/bodega.py) =====
-- Sitios donde se guardan cosas: hangar, pista, base de operación, vehículo de apoyo.
CREATE TABLE IF NOT EXISTS bodega_ubicaciones(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'hangar',
  detalle TEXT,
  activo INTEGER NOT NULL DEFAULT 1,
  creado {_AHORA},
  UNIQUE(empresa_id, id)
);

-- Artículos de las dos bodegas: `clase` repuesto (piezas de drones y del avión, enlazadas al
-- catálogo por `catalogo` + `catalogo_ref`) o insumo (fitosanitarios, aceite agrícola,
-- coadyuvantes, fertilizantes, aceite de motor…). Las existencias y el costo promedio no se
-- guardan: se reconstruyen con los movimientos, igual que el nivel de los depósitos de combustible.
CREATE TABLE IF NOT EXISTS bodega_items(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  clase TEXT NOT NULL DEFAULT 'repuesto',
  nombre TEXT NOT NULL,
  codigo TEXT,
  modelo TEXT,
  catalogo TEXT,
  catalogo_ref TEXT,
  categoria TEXT,
  ingrediente_activo TEXT,
  concentracion TEXT,
  categoria_tox TEXT,
  registro_ica TEXT,
  unidad TEXT NOT NULL DEFAULT 'und',
  presentacion TEXT,
  contenido DOUBLE PRECISION,
  stock_minimo DOUBLE PRECISION NOT NULL DEFAULT 0,
  cantidad_cambio DOUBLE PRECISION NOT NULL DEFAULT 1,
  dosis_ha DOUBLE PRECISION,
  proveedor TEXT,
  costo_referencia DOUBLE PRECISION,
  color TEXT,
  serializado INTEGER NOT NULL DEFAULT 0,
  activo INTEGER NOT NULL DEFAULT 1,
  nota TEXT,
  creado {_AHORA},
  UNIQUE(empresa_id, id)
);

-- Tanques y tambores de insumos a granel. El usuario elige qué contiene cada uno (`item_id`);
-- el nivel sale de los movimientos que entran o salen de ese tanque.
CREATE TABLE IF NOT EXISTS bodega_tanques(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  item_id INTEGER,
  ubicacion_id INTEGER,
  capacidad DOUBLE PRECISION NOT NULL DEFAULT 0,
  forma TEXT NOT NULL DEFAULT 'tanque',
  color TEXT,
  activo INTEGER NOT NULL DEFAULT 1,
  nota TEXT,
  creado {_AHORA},
  UNIQUE(empresa_id, id),
  FOREIGN KEY(empresa_id, item_id) REFERENCES bodega_items(empresa_id, id) ON DELETE SET NULL (item_id),
  FOREIGN KEY(empresa_id, ubicacion_id) REFERENCES bodega_ubicaciones(empresa_id, id) ON DELETE SET NULL (ubicacion_id)
);

-- Kardex: entrada (compra), salida (consumo, OT, operación), traslado entre ubicaciones, ajuste
-- por conteo físico (`conteo` = lo contado; `cantidad` = descuadre con signo) y baja (vencido,
-- dañado). `costo_unitario` en una entrada es el precio de compra; en una salida, el costo
-- promedio con que salió.
CREATE TABLE IF NOT EXISTS bodega_movimientos(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'salida',
  fecha {_FECHA},
  item_id INTEGER NOT NULL,
  ubicacion_id INTEGER,
  destino_id INTEGER,
  tanque_id INTEGER,
  tanque_destino_id INTEGER,
  cantidad DOUBLE PRECISION NOT NULL DEFAULT 0,
  conteo DOUBLE PRECISION,
  costo_unitario DOUBLE PRECISION,
  lote TEXT,
  vence TEXT,
  serie TEXT,
  proveedor TEXT,
  documento TEXT,
  motivo TEXT,
  equipo_id INTEGER,
  orden_id INTEGER,
  ot_linea_id INTEGER,
  operacion_id INTEGER,
  responsable TEXT,
  nota TEXT,
  usuario TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, item_id) REFERENCES bodega_items(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY(empresa_id, ubicacion_id) REFERENCES bodega_ubicaciones(empresa_id, id) ON DELETE SET NULL (ubicacion_id),
  FOREIGN KEY(empresa_id, destino_id) REFERENCES bodega_ubicaciones(empresa_id, id) ON DELETE SET NULL (destino_id),
  FOREIGN KEY(empresa_id, tanque_id) REFERENCES bodega_tanques(empresa_id, id) ON DELETE SET NULL (tanque_id),
  FOREIGN KEY(empresa_id, tanque_destino_id) REFERENCES bodega_tanques(empresa_id, id) ON DELETE SET NULL (tanque_destino_id),
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE SET NULL (equipo_id),
  FOREIGN KEY(empresa_id, orden_id) REFERENCES ordenes_trabajo(empresa_id, id) ON DELETE SET NULL (orden_id)
);
CREATE INDEX IF NOT EXISTS ix_bod_mov_item ON bodega_movimientos(item_id, fecha);
CREATE INDEX IF NOT EXISTS ix_bod_mov_fecha ON bodega_movimientos(fecha);
CREATE INDEX IF NOT EXISTS ix_bod_mov_op ON bodega_movimientos(operacion_id);

-- Repuestos de bodega apartados para una orden de trabajo (y para una tarea concreta). Al
-- completar la orden se descuentan (estado «consumido», con su movimiento de salida); si la
-- orden se reabre o se borra, la salida se deshace.
CREATE TABLE IF NOT EXISTS bodega_ot_lineas(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  orden_id INTEGER NOT NULL,
  tarea_id INTEGER,
  item_id INTEGER NOT NULL,
  ubicacion_id INTEGER,
  cantidad DOUBLE PRECISION NOT NULL DEFAULT 1,
  estado TEXT NOT NULL DEFAULT 'reservado',
  costo_unitario DOUBLE PRECISION,
  movimiento_id INTEGER,
  usuario TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, orden_id) REFERENCES ordenes_trabajo(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY(empresa_id, item_id) REFERENCES bodega_items(empresa_id, id) ON DELETE CASCADE,
  FOREIGN KEY(empresa_id, ubicacion_id) REFERENCES bodega_ubicaciones(empresa_id, id) ON DELETE SET NULL (ubicacion_id)
);
CREATE INDEX IF NOT EXISTS ix_bod_ot ON bodega_ot_lineas(orden_id);

-- Productos aplicados en cada operación (RAC 137.71(3): nombre y cantidad de lo aplicado, se
-- conserva al menos 12 meses). `cantidad_teorica` = hectáreas × dosis; `movimiento_id` es la
-- salida de bodega con que se descontó (vacío si aún no se concilió).
CREATE TABLE IF NOT EXISTS bodega_aplicaciones(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  operacion_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  dosis_ha DOUBLE PRECISION,
  hectareas DOUBLE PRECISION,
  cantidad_teorica DOUBLE PRECISION,
  movimiento_id INTEGER,
  usuario TEXT,
  creado {_AHORA},
  FOREIGN KEY(empresa_id, item_id) REFERENCES bodega_items(empresa_id, id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_bod_apl_op ON bodega_aplicaciones(operacion_id);

-- ===== Incidentes (core/incidentes.py) =====
-- Golpe, caída, aterrizaje duro, colisión… Mientras un incidente no tenga su inspección cerrada el
-- activo queda «No recomendado volar». La inspección la firma, en un avión, el inspector o
-- mecánico certificador (con licencia); en un dron, el técnico asignado o el representante del
-- fabricante.
CREATE TABLE IF NOT EXISTS incidentes(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  equipo_id INTEGER NOT NULL,
  fecha TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'otro',
  descripcion TEXT NOT NULL,
  danos TEXT,
  lugar TEXT,
  piloto TEXT,
  operacion_id INTEGER,
  orden_id INTEGER,
  estado TEXT NOT NULL DEFAULT 'abierto',
  inspeccion_fecha TEXT,
  inspeccion_resultado TEXT,
  inspeccion_firmado_por TEXT,
  inspeccion_cargo TEXT,
  inspeccion_licencia TEXT,
  inspeccion_nota TEXT,
  inspeccion_usuario TEXT,
  usuario TEXT,
  creado {_AHORA},
  UNIQUE(empresa_id, id),
  FOREIGN KEY(empresa_id, equipo_id) REFERENCES equipos(empresa_id, id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_incidentes_equipo ON incidentes(equipo_id, estado);

-- ===== Envases de agroquímicos (core/bodega.py) =====
-- Triple lavado y devolución de envases vacíos al programa posconsumo: lo piden GlobalG.A.P.,
-- Rainforest Alliance y las auditorías del cliente. Un registro por lote de envases.
CREATE TABLE IF NOT EXISTS envases(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  fecha TEXT NOT NULL,
  producto TEXT NOT NULL,
  cliente TEXT,
  operacion_id INTEGER,
  orden_servicio TEXT,
  cantidad INTEGER NOT NULL DEFAULT 1,
  capacidad TEXT,
  triple_lavado INTEGER NOT NULL DEFAULT 0,
  perforado INTEGER NOT NULL DEFAULT 0,
  lavado_por TEXT,
  devuelto_en TEXT,
  centro_acopio TEXT,
  certificado TEXT,
  archivo TEXT,
  nota TEXT,
  usuario TEXT,
  creado {_AHORA}
);
CREATE INDEX IF NOT EXISTS ix_envases_fecha ON envases(fecha);

-- Criterio de rechazo escrito de cada pieza «on-condition» (sin plazo del fabricante): qué hay que
-- ver para cambiarla. Es de cada empresa, también para las piezas del catálogo del sistema.
CREATE TABLE IF NOT EXISTS criterios_rechazo(
  id {_ID},
  empresa_id INTEGER NOT NULL DEFAULT empresa_actual() REFERENCES empresas(id) ON DELETE CASCADE,
  pieza_id INTEGER NOT NULL REFERENCES catalogo_piezas(id) ON DELETE CASCADE,
  texto TEXT NOT NULL,
  usuario TEXT,
  actualizado {_AHORA},
  UNIQUE(empresa_id, pieza_id)
);
"""


# Tablas con datos de empresa: llevan empresa_id, índice por empresa y política RLS.
TABLAS_EMPRESA = ["meta", "equipos", "registros", "componentes", "operaciones", "mantenimientos",
                  "personal", "ordenes_trabajo", "ot_tareas", "ordenes_servicio", "os_productos",
                  "os_eventos", "correo_cola",
                  # Flota mixta (core/flota.py)
                  "contadores_equipo", "piezas_serie", "instalaciones", "directivas",
                  "cumplimiento_directiva", "documentos", "tarifas", "auditoria", "checklists",
                  "estado_diario", "combustible_depositos", "combustible_movimientos",
                  # Bodega (core/bodega.py)
                  "bodega_ubicaciones", "bodega_items", "bodega_tanques", "bodega_movimientos",
                  "bodega_ot_lineas", "bodega_aplicaciones",
                  # Encuesta de validación: incidentes y envases
                  "incidentes", "envases", "criterios_rechazo"]

# Tablas con filas globales (sembradas por el sistema, empresa_id nulo) y filas propias de cada
# empresa: cada empresa ve las globales más las suyas y sólo puede escribir las suyas.
TABLAS_MIXTAS = ["modelos_activo", "catalogo_piezas"]

RLS = "".join(f"""
CREATE INDEX IF NOT EXISTS ix_{t}_empresa ON {t}(empresa_id);
ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {t} FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS aislamiento_{t} ON {t};
CREATE POLICY aislamiento_{t} ON {t}
  USING (current_setting('app.empresa_id', true) = '*' OR empresa_id = empresa_actual())
  WITH CHECK (current_setting('app.empresa_id', true) = '*' OR empresa_id = empresa_actual());
""" for t in TABLAS_EMPRESA) + "".join(f"""
CREATE INDEX IF NOT EXISTS ix_{t}_empresa ON {t}(empresa_id);
ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {t} FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS aislamiento_{t} ON {t};
CREATE POLICY aislamiento_{t} ON {t}
  USING (current_setting('app.empresa_id', true) = '*' OR empresa_id IS NULL OR empresa_id = empresa_actual())
  WITH CHECK (current_setting('app.empresa_id', true) = '*' OR empresa_id = empresa_actual());
""" for t in TABLAS_MIXTAS)


# Tablas de la app, en orden de dependencias (sirve para migrar y para vaciar).
TABLAS = ["empresas", "usuarios", "meta", "login_intentos", "equipos", "registros", "catalogo_piezas",
          "catalogo_despiece", "componentes", "operaciones", "mantenimientos", "personal",
          "ordenes_trabajo", "ot_tareas", "ordenes_servicio", "os_productos", "os_eventos",
          "correo_cola", "modelos_activo", "contadores_equipo", "piezas_serie", "instalaciones",
          "directivas", "cumplimiento_directiva", "documentos", "tarifas", "auditoria", "checklists",
          "estado_diario", "combustible_depositos", "combustible_movimientos",
          "bodega_ubicaciones", "bodega_items", "bodega_tanques", "bodega_movimientos",
          "bodega_ot_lineas", "bodega_aplicaciones", "incidentes", "envases", "criterios_rechazo"]


TODAS = "*"   # valor de app.empresa_id que desactiva el filtro (sólo administración)

ES_SQLITE = core_conexion.ES_SQLITE
EMPRESA_ESCRITORIO = 1   # en el escritorio hay una sola empresa


def a_sqlite(ddl):
    """Traduce el esquema (dialecto PostgreSQL) a SQLite."""
    import re
    ddl = re.sub(r"CREATE OR REPLACE FUNCTION.*?LANGUAGE sql[^;]*;", "", ddl, flags=re.S)
    ddl = ddl.replace(_ID, "INTEGER PRIMARY KEY AUTOINCREMENT")
    ddl = ddl.replace("to_char(CURRENT_DATE, 'YYYY-MM-DD')", "(date('now','localtime'))")
    ddl = ddl.replace("to_char(now(), 'YYYY-MM-DD HH24:MI:SS')", "(datetime('now','localtime'))")
    ddl = ddl.replace("TIMESTAMPTZ DEFAULT now()", "TEXT DEFAULT (datetime('now','localtime'))")
    ddl = ddl.replace("DEFAULT empresa_actual()", f"DEFAULT {EMPRESA_ESCRITORIO}")
    # FK compuesta (empresa_id, x) -> FK simple sobre x; «SET NULL (x)» -> «SET NULL».
    ddl = re.sub(r"FOREIGN KEY\(empresa_id, (\w+)\) REFERENCES (\w+)\(empresa_id, id\) ON DELETE SET NULL \(\w+\)",
                 r"FOREIGN KEY(\1) REFERENCES \2(id) ON DELETE SET NULL", ddl)
    ddl = re.sub(r"FOREIGN KEY\(empresa_id, (\w+)\) REFERENCES (\w+)\(empresa_id, id\)",
                 r"FOREIGN KEY(\1) REFERENCES \2(id)", ddl)
    return ddl


def conectar(empresa_id=None):
    """Conexión con la empresa fijada. `empresa_id=None` deja la conexión SIN empresa: las
    tablas de datos devuelven vacío y rechazan escrituras (es lo que ve la pantalla de acceso).
    `conectar(TODAS)` ve todas las empresas: sólo para migraciones y tareas de administración."""
    con = core_conexion.conectar()
    con.fijar_empresa(empresa_id)
    return con


def inicializar(sembrar=True):
    """Crea lo que falte del esquema y siembra los catálogos de piezas. Es idempotente."""
    con = conectar(TODAS)
    if ES_SQLITE:
        _inicializar_sqlite(con)
    else:
        # Varios procesos pueden arrancar a la vez (workers de Gunicorn en desarrollo, réplicas en
        # el servidor): el candado de sesión hace que migren de a uno; se suelta al cerrar `con`.
        con.execute("SELECT pg_advisory_lock(4826001)")
        con.commit()
        _inicializar_postgres(con)
    if sembrar:
        for clave in core_modelos.claves():
            _sembrar_catalogo(con, clave)
            _sembrar_despiece(con, clave)
        for clave in core_modelos.AVIONES:
            _sembrar_despiece_avion(con, clave)
        core_flota.sembrar_modelos(con, core_modelos.MODELOS, core_aeronaves.PLANTILLAS)
        # Piezas nuevas del catálogo DJI llegan también a los drones ya creados.
        for clave in core_modelos.claves():
            core_flota.completar_componentes(con, clave)
    core_flota.conciliar(con)
    con.commit()
    con.close()


def _inicializar_sqlite(con):
    con.executescript(a_sqlite(ESQUEMA))
    for tabla, columnas in COLUMNAS_FLOTA.items():
        _añadir_columnas(con, tabla, {k: a_sqlite(v) for k, v in columnas.items()})
    con.executescript(a_sqlite(ESQUEMA_FLOTA))
    for tabla, columnas in COLUMNAS_POSTERIORES.items():
        _añadir_columnas(con, tabla, {k: a_sqlite(v) for k, v in columnas.items()})
    for t in TABLAS_EMPRESA + TABLAS_MIXTAS:
        con.execute(f"CREATE INDEX IF NOT EXISTS ix_{t}_empresa ON {t}(empresa_id)")
    if not con.execute("SELECT 1 FROM empresas WHERE id=?", (EMPRESA_ESCRITORIO,)).fetchone():
        con.execute("INSERT INTO empresas(id, nombre) VALUES(?, 'Mi empresa')", (EMPRESA_ESCRITORIO,))
    con.commit()


def _inicializar_postgres(con):
    _migrar_multiempresa(con)
    con.executescript(ESQUEMA)
    # Columnas añadidas después de la primera versión (bases ya creadas no las traen).
    _añadir_columnas(con, "usuarios", {"nombre": "TEXT", "email": "TEXT",
                                       "rol": "TEXT NOT NULL DEFAULT 'admin'",
                                       "activo": "INTEGER NOT NULL DEFAULT 1", "ultimo_acceso": "TEXT",
                                       "empresa_id": "INTEGER REFERENCES empresas(id) ON DELETE CASCADE"})
    for tabla, columnas in COLUMNAS_FLOTA.items():
        _añadir_columnas(con, tabla, columnas)
    con.executescript(ESQUEMA_FLOTA)
    for tabla, columnas in COLUMNAS_POSTERIORES.items():
        _añadir_columnas(con, tabla, columnas)
    _arreglar_set_null(con)
    con.executescript(RLS)
    con.commit()


def _añadir_columnas(con, tabla, columnas):
    """ALTER TABLE idempotente para bases creadas antes de una versión."""
    for nombre, tipo in columnas.items():
        if ES_SQLITE:
            if _existe_tabla(con, tabla) and not _tiene_columna(con, tabla, nombre):
                # SQLite no admite añadir columnas con REFERENCES+DEFAULT no constante: se quita la FK.
                import re
                con.execute(f"ALTER TABLE {tabla} ADD COLUMN {nombre} {re.sub(r' REFERENCES .*$', '', tipo)}")
        else:
            con.execute(f"ALTER TABLE {tabla} ADD COLUMN IF NOT EXISTS {nombre} {tipo}")


def _existe_tabla(con, tabla):
    if ES_SQLITE:
        return bool(con.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (tabla,)).fetchone())
    return bool(con.execute("SELECT 1 FROM information_schema.tables WHERE table_name=?", (tabla,)).fetchone())


def _tiene_columna(con, tabla, columna):
    if ES_SQLITE:
        return any(f["name"] == columna for f in con.execute(f"PRAGMA table_info({tabla})").fetchall())
    return bool(con.execute("SELECT 1 FROM information_schema.columns WHERE table_name=? AND column_name=?",
                            (tabla, columna)).fetchone())


def _migrar_multiempresa(con):
    """Pasa una base de una sola empresa al esquema multi-empresa.

    Todo lo que ya existía pasa a ser de la empresa 1 («Empresa principal»). La clave primaria
    de `meta` y los códigos únicos de las órdenes pasan a ser únicos POR empresa.
    """
    if not _existe_tabla(con, "equipos") or _tiene_columna(con, "equipos", "empresa_id"):
        return
    con.executescript(ESQUEMA.split("CREATE TABLE IF NOT EXISTS meta(")[0])   # función + empresas
    if not con.execute("SELECT 1 FROM empresas").fetchone():
        con.execute("INSERT INTO empresas(id, nombre) VALUES(1, 'Empresa principal')")
        con.execute("SELECT setval(pg_get_serial_sequence('empresas','id'), 1)")
    for t in TABLAS_EMPRESA:
        if not _existe_tabla(con, t):
            continue
        con.execute(f"ALTER TABLE {t} ADD COLUMN IF NOT EXISTS empresa_id INTEGER")
        con.execute(f"UPDATE {t} SET empresa_id=1 WHERE empresa_id IS NULL")
        con.execute(f"ALTER TABLE {t} ALTER COLUMN empresa_id SET NOT NULL, "
                    f"ALTER COLUMN empresa_id SET DEFAULT empresa_actual()")
        con.execute(f"ALTER TABLE {t} ADD CONSTRAINT fk_{t}_empresa FOREIGN KEY(empresa_id) "
                    f"REFERENCES empresas(id) ON DELETE CASCADE")
    con.execute("ALTER TABLE meta DROP CONSTRAINT IF EXISTS meta_pkey")
    con.execute("ALTER TABLE meta ADD PRIMARY KEY(empresa_id, clave)")
    for t in ("ordenes_trabajo", "ordenes_servicio"):
        con.execute(f"ALTER TABLE {t} DROP CONSTRAINT IF EXISTS {t}_codigo_key")
        con.execute(f"ALTER TABLE {t} ADD CONSTRAINT {t}_empresa_codigo_key UNIQUE(empresa_id, codigo)")
    con.execute("ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS empresa_id INTEGER REFERENCES empresas(id) ON DELETE CASCADE")
    con.execute("UPDATE usuarios SET empresa_id=1 WHERE empresa_id IS NULL")
    _reforzar_fks(con)
    con.commit()


# Claves foráneas COMPUESTAS (empresa_id, id): PostgreSQL no aplica RLS a las comprobaciones de
# clave foránea, así que sin esto una orden de una empresa podría apuntar a un dron de otra.
_FKS_COMPUESTAS = [
    # (tabla hija, columna, tabla padre, acción)
    ("registros", "equipo_id", "equipos", "SET NULL"),
    ("componentes", "equipo_id", "equipos", "CASCADE"),
    ("operaciones", "equipo_id", "equipos", "CASCADE"),
    ("mantenimientos", "equipo_id", "equipos", "CASCADE"),
    ("mantenimientos", "componente_id", "componentes", "SET NULL"),
    ("ordenes_trabajo", "equipo_id", "equipos", "CASCADE"),
    ("ot_tareas", "orden_id", "ordenes_trabajo", "CASCADE"),
    ("ot_tareas", "componente_id", "componentes", "SET NULL"),
    ("ordenes_servicio", "equipo_id", "equipos", "SET NULL"),
    ("os_productos", "orden_id", "ordenes_servicio", "CASCADE"),
    ("os_eventos", "orden_id", "ordenes_servicio", "CASCADE"),
]


def _reforzar_fks(con):
    for padre in ("equipos", "componentes", "ordenes_trabajo", "ordenes_servicio"):
        if not con.execute("SELECT 1 FROM pg_constraint WHERE conname=?", (f"{padre}_empresa_id_id_key",)).fetchone():
            con.execute(f"ALTER TABLE {padre} ADD CONSTRAINT {padre}_empresa_id_id_key UNIQUE(empresa_id, id)")
    for hija, col, padre, accion in _FKS_COMPUESTAS:
        con.execute(f"ALTER TABLE {hija} DROP CONSTRAINT IF EXISTS {hija}_{col}_fkey")
        nombre = f"{hija}_empresa_{col}_fkey"
        if not con.execute("SELECT 1 FROM pg_constraint WHERE conname=?", (nombre,)).fetchone():
            con.execute(f"ALTER TABLE {hija} ADD CONSTRAINT {nombre} FOREIGN KEY(empresa_id, {col}) "
                        f"REFERENCES {padre}(empresa_id, id) ON DELETE {accion}")
    _arreglar_set_null(con)


def _arreglar_set_null(con):
    """ON DELETE SET NULL sobre una clave compuesta (empresa_id, x) pone en nulo también
    empresa_id, que es NOT NULL: borrar un dron con órdenes o piezas fallaba. PostgreSQL 15+
    permite limitarlo a la columna de la referencia: SET NULL (x)."""
    filas = con.execute(
        """SELECT c.conname, c.conrelid::regclass::text tabla, pg_get_constraintdef(c.oid) d
           FROM pg_constraint c WHERE c.contype='f' AND pg_get_constraintdef(c.oid) LIKE '%(empresa_id, %ON DELETE SET NULL'""").fetchall()
    for f in filas:
        col = f["d"].split("(empresa_id, ", 1)[1].split(")", 1)[0]
        nuevo = f["d"] + f" ({col})"
        con.execute(f'ALTER TABLE {f["tabla"]} DROP CONSTRAINT {f["conname"]}')
        con.execute(f'ALTER TABLE {f["tabla"]} ADD CONSTRAINT {f["conname"]} {nuevo}')


def _sembrar_catalogo(con, modelo):
    """Vuelca las piezas con vida útil de un modelo (core/modelos.py).

    Las piezas que se retiran del catálogo (una carga de pago que la flota no monta, por ejemplo)
    se borran también de la base: si no, seguirían generando alertas de un equipo que no existe.
    La bitácora de reparaciones no se pierde — guarda el código y el nombre de la pieza aparte.
    """
    claves = [c[0] for c in core_modelos.catalogo(modelo)]
    if claves:
        marcas = ",".join("?" * len(claves))
        con.execute(f"DELETE FROM catalogo_piezas WHERE modelo=? AND clave NOT IN ({marcas})",
                    [modelo] + claves)
    for clave, modulo, nombre, vida_h, vida_m, nota, mesh in core_modelos.catalogo(modelo):
        con.execute(
            "INSERT INTO catalogo_piezas(modelo, clave, modulo, nombre, vida_util_horas, "
            "                            vida_util_meses, nota, mesh) VALUES(?,?,?,?,?,?,?,?) "
            "ON CONFLICT(modelo, clave) DO UPDATE SET "
            "modulo=excluded.modulo, nombre=excluded.nombre, "
            "vida_util_horas=excluded.vida_util_horas, vida_util_meses=excluded.vida_util_meses, "
            "nota=excluded.nota, mesh=excluded.mesh",
            (modelo, clave, modulo, nombre, vida_h, vida_m, nota, mesh),
        )
    con.commit()


# Las zonas viven en core/modelos.py, que es donde está todo lo que depende del modelo. Se
# reexportan aquí porque el resto del código las venía pidiendo a este módulo.
ZONA_DE_MODULO = core_modelos.ZONA_DE_MODULO_T50
ZONA_SUELTA = core_modelos.ZONA_SUELTA


def zonas_de_catalogo(modelo):
    """Zona de cada pieza con vida útil, deducida de la lámina en la que DJI la dibuja."""
    salida = dict(ZONA_SUELTA)
    for m in core_modelos.cargar_diagramas(modelo):
        for clave in m.get("piezas_catalogo") or []:
            # Una pieza puede salir en dos láminas (el motor está en los cuatro brazos); las
            # láminas hermanas caen en la misma zona, así que no hay ambigüedad que resolver.
            salida.setdefault(clave, m["zona"])
    return salida


def _sembrar_despiece(con, modelo):
    """Vuelca en la base el despiece de las láminas oficiales de un modelo.

    Los nombres en castellano vienen precalculados en el JSON con el mismo traductor que usa la
    pantalla de diagramas, para que una pieza se llame igual en el buscador, en la lámina y en
    la bitácora.
    """
    modulos = core_modelos.cargar_diagramas(modelo)
    # Las láminas que ya no existen (renombradas o retiradas del JSON) se van con sus piezas: si
    # no, el despiece del modelo arrastra para siempre las claves viejas.
    claves = [m["clave"] for m in modulos]
    if claves:
        marcas = ",".join("?" * len(claves))
        con.execute(f"DELETE FROM catalogo_despiece WHERE modelo=? AND modulo_clave NOT IN ({marcas})",
                    [modelo] + claves)
    for modulo in modulos:
        # Las variantes de un mismo número (lado, serie, equipo opcional: sólo en los aviones) se
        # buscan igual que la principal.
        filas = [v for p in modulo.get("partes") or []
                 for v in [p] + [dict(x, n=p["n"], auxiliar=p.get("auxiliar")) for x in p.get("variantes") or []]]
        for parte in filas:
            con.execute(
                "INSERT INTO catalogo_despiece(modelo, codigo, nombre, nombre_en, nombre_zh, "
                "                              modulo_clave, modulo, n, auxiliar) "
                "VALUES(?,?,?,?,?,?,?,?,?) "
                "ON CONFLICT(modelo, modulo_clave, n, codigo) DO UPDATE SET "
                "nombre=excluded.nombre, nombre_en=excluded.nombre_en, nombre_zh=excluded.nombre_zh, "
                "modulo=excluded.modulo, auxiliar=excluded.auxiliar",
                (modelo, parte.get("codigo") or "",
                 parte.get("nombre_es") or parte.get("nombre_en") or "",
                 parte.get("nombre_en"), parte.get("nombre_zh"), modulo.get("clave"),
                 modulo.get("nombre") or modulo.get("clave"), parte.get("n"),
                 1 if parte.get("auxiliar") else 0),
            )
        con.execute("UPDATE catalogo_despiece SET zona=? WHERE modelo=? AND modulo_clave=?",
                    (modulo["zona"], modelo, modulo["clave"]))
    for clave, zona in zonas_de_catalogo(modelo).items():
        con.execute("UPDATE catalogo_piezas SET zona=? WHERE modelo=? AND clave=?",
                    (zona, modelo, clave))
    # Cualquier pieza sin zona conocida se queda con su familia funcional, que es mejor que nada.
    con.execute("UPDATE catalogo_piezas SET zona=modulo WHERE zona IS NULL OR zona=''")
    con.commit()


def _sembrar_despiece_avion(con, clave):
    """El catálogo de un avión son miles de piezas: sólo se vuelca si la base no tiene ya las
    mismas láminas y el mismo número de piezas que su JSON."""
    modulos = core_modelos.cargar_diagramas(clave)
    esperado = (len(modulos), len({(m["clave"], p["n"], v.get("codigo") or "") for m in modulos
                                   for p in m.get("partes") or [] for v in [p] + (p.get("variantes") or [])}))
    fila = con.execute("SELECT COUNT(DISTINCT modulo_clave) l, COUNT(*) n FROM catalogo_despiece WHERE modelo=?",
                       (clave,)).fetchone()
    if modulos and (fila["l"], fila["n"]) != esperado:
        _sembrar_despiece(con, clave)


def piezas_catalogo_por_modulo(modelo):
    """Qué piezas con vida útil cuelga cada lámina del despiece de un modelo."""
    return {m["clave"]: (m.get("piezas_catalogo") or [])
            for m in core_modelos.cargar_diagramas(modelo)}


def meta_get(con, clave, defecto=None):
    fila = con.execute("SELECT valor FROM meta WHERE clave=?", (clave,)).fetchone()
    return fila["valor"] if fila else defecto


def meta_set(con, clave, valor):
    con.execute(
        "INSERT INTO meta(clave, valor) VALUES(?,?) "
        "ON CONFLICT(empresa_id, clave) DO UPDATE SET valor=excluded.valor",
        (clave, valor),
    )
    con.commit()


ROLES_USUARIO = {"admin": "Administrador", "tecnico": "Técnico", "certificador": "Mecánico certificador",
                 "piloto": "Piloto", "gerencia": "Gerencia / finanzas"}
# Quién ve la plata: ingreso, tarifas, nómina, margen (la gerencia lo pidió así en la encuesta).
ROLES_COSTOS = ("admin", "superadmin", "gerencia")
ROL_SUPERADMIN = "superadmin"   # gestiona las empresas; puede entrar a cualquiera


def crear_usuario(con, usuario, password, rol="admin", nombre=None, email=None, empresa_id=None):
    if rol not in ROLES_USUARIO and rol != ROL_SUPERADMIN:
        raise ValueError("rol no válido")
    if empresa_id is None:
        empresa_id = con.empresa_id if con.empresa_id not in (None, TODAS) else None
    cur = con.execute(
        "INSERT INTO usuarios(usuario, password_hash, rol, nombre, email, empresa_id) VALUES(?,?,?,?,?,?)",
        (usuario, generate_password_hash(password), rol, nombre, email, empresa_id),
    )
    con.commit()
    return cur.lastrowid


# ---------- Empresas ----------

def crear_empresa(con, nombre, nit=None, contacto=None, email=None, telefono=None, nota=None):
    cur = con.execute(
        "INSERT INTO empresas(nombre, nit, contacto, email, telefono, nota) VALUES(?,?,?,?,?,?)",
        (nombre.strip(), nit, contacto, email, telefono, nota))
    con.commit()
    return cur.lastrowid


def empresas(con):
    """Empresas con su actividad, para el panel del superadministrador (conexión TODAS)."""
    return [dict(f) for f in con.execute(
        """SELECT e.*,
                  (SELECT COUNT(*) FROM usuarios u WHERE u.empresa_id=e.id) n_usuarios,
                  (SELECT COUNT(*) FROM usuarios u WHERE u.empresa_id=e.id AND u.activo=1) n_usuarios_activos,
                  (SELECT COUNT(*) FROM equipos q WHERE q.empresa_id=e.id AND q.estado!='baja') n_equipos,
                  (SELECT COUNT(*) FROM operaciones o WHERE o.empresa_id=e.id) n_operaciones,
                  (SELECT MAX(o.fecha) FROM operaciones o WHERE o.empresa_id=e.id) ultima_operacion,
                  (SELECT MAX(u.ultimo_acceso) FROM usuarios u WHERE u.empresa_id=e.id) ultimo_acceso,
                  (SELECT COUNT(*) FROM ordenes_trabajo t WHERE t.empresa_id=e.id
                     AND t.estado NOT IN ('completada','cancelada')) ot_abiertas
           FROM empresas e ORDER BY e.activa DESC, e.nombre""").fetchall()]


def totales_plataforma(con):
    return dict(con.execute(
        """SELECT (SELECT COUNT(*) FROM empresas) empresas,
                  (SELECT COUNT(*) FROM empresas WHERE activa=1) empresas_activas,
                  (SELECT COUNT(*) FROM usuarios WHERE rol!='superadmin') usuarios,
                  (SELECT COUNT(*) FROM equipos WHERE estado!='baja') equipos,
                  (SELECT COUNT(*) FROM operaciones) operaciones,
                  (SELECT COUNT(*) FROM operaciones WHERE fecha >= to_char(CURRENT_DATE - 30, 'YYYY-MM-DD')) operaciones_30d
        """).fetchone())


def series_plataforma(con, semanas=12):
    """Tendencia de las últimas `semanas` para el panel: acumulado de empresas, usuarios y
    drones existentes al cierre de cada semana, y operaciones registradas en cada semana.
    Devuelve listas de `semanas` valores (la última posición es la semana actual) y las
    variaciones de los últimos 30 días frente a los 30 anteriores."""
    dias = lambda col: core_conexion.sql_dias(col, core_conexion.sql_hoy())   # días desde col hasta hoy

    def acumulado(tabla, filtro=""):
        # Altas por semana (semanas ISO relativas a hoy) más lo que ya existía antes del rango.
        filas = con.execute(f"""
            SELECT LEAST({semanas - 1}, GREATEST(-1,
                     {semanas - 1} - ({dias('creado')} / 7))) AS semana,
                   COUNT(*) n
            FROM {tabla} WHERE creado IS NOT NULL {filtro}
            GROUP BY 1""").fetchall()
        por_semana = {int(f["semana"]): int(f["n"]) for f in filas}
        total, serie = por_semana.get(-1, 0), []
        for i in range(semanas):
            total += por_semana.get(i, 0)
            serie.append(total)
        return serie

    def altas_30d(tabla, filtro=""):
        f = con.execute(f"""
            SELECT COUNT(*) FILTER (WHERE {dias('creado')} <= 30) reciente,
                   COUNT(*) FILTER (WHERE {dias('creado')} <= 60 AND {dias('creado')} > 30) anterior
            FROM {tabla} WHERE creado IS NOT NULL {filtro}""").fetchone()
        return {"reciente": int(f["reciente"] or 0), "anterior": int(f["anterior"] or 0)}

    ops = con.execute(f"""
        SELECT {semanas - 1} - ({dias('fecha')} / 7) AS semana, COUNT(*) n
        FROM operaciones
        WHERE fecha >= to_char(CURRENT_DATE - {semanas * 7 - 1}, 'YYYY-MM-DD')
        GROUP BY 1""").fetchall()
    por_semana = {int(f["semana"]): int(f["n"]) for f in ops}
    ops_30 = con.execute(f"""
        SELECT COUNT(*) FILTER (WHERE {dias('fecha')} <= 30) reciente,
               COUNT(*) FILTER (WHERE {dias('fecha')} <= 60 AND {dias('fecha')} > 30) anterior
        FROM operaciones WHERE fecha >= to_char(CURRENT_DATE - 60, 'YYYY-MM-DD')""").fetchone()
    return {
        "empresas": {"serie": acumulado("empresas", "AND activa=1"), **altas_30d("empresas", "AND activa=1")},
        "usuarios": {"serie": acumulado("usuarios", "AND rol!='superadmin'"), **altas_30d("usuarios", "AND rol!='superadmin'")},
        "equipos": {"serie": acumulado("equipos", "AND estado!='baja'"), **altas_30d("equipos", "AND estado!='baja'")},
        "operaciones": {"serie": [por_semana.get(i, 0) for i in range(semanas)],
                        "reciente": int(ops_30["reciente"] or 0), "anterior": int(ops_30["anterior"] or 0)},
    }


def empresa(con, empresa_id):
    return con.execute("SELECT * FROM empresas WHERE id=?", (empresa_id,)).fetchone()


def cambiar_password(con, usuario, password):
    con.execute("UPDATE usuarios SET password_hash=?, debe_cambiar_password=0 WHERE usuario=?",
                (generate_password_hash(password), usuario))
    con.commit()


def sembrar_superadmin(con, usuario, password=None):
    """Primer despliegue: si la base no tiene ninguna cuenta, crea el superadministrador con una
    contraseña temporal que hay que cambiar al entrar. Sin `password` se genera una aleatoria.
    Devuelve (usuario, contraseña) si lo creó, o None si ya había cuentas (no toca nada)."""
    if hay_usuarios(con):
        return None
    password = password or secrets.token_urlsafe(12)
    crear_usuario(con, usuario, password, rol=ROL_SUPERADMIN, empresa_id=None)
    con.execute("UPDATE usuarios SET debe_cambiar_password=1 WHERE usuario=?", (usuario,))
    con.commit()
    return usuario, password


def usuario_por_nombre(con, usuario):
    return con.execute("SELECT * FROM usuarios WHERE usuario=?", (usuario,)).fetchone()


def usuarios(con, empresa_id=None):
    """Cuentas de UNA empresa (la de la conexión si no se indica otra)."""
    if empresa_id is None:
        empresa_id = con.empresa_id
    return [dict(f) for f in con.execute(
        "SELECT id, usuario, nombre, email, rol, activo, ultimo_acceso, creado, empresa_id "
        "FROM usuarios WHERE empresa_id=? ORDER BY usuario", (empresa_id,)).fetchall()]


def hay_usuarios(con):
    return con.execute("SELECT COUNT(*) n FROM usuarios").fetchone()["n"] > 0


# ---------- Equipos y componentes ----------

def crear_equipo(con, nombre, modelo, numero_serie, nota=None, tipo_activo=None, matricula=None,
                 anio=None, base=None, fabricante=None, contadores=None, fecha_alta=None):
    """Da de alta un activo (dron o avión) con los componentes de SU modelo y sus contadores.

    Para un avión se pasan las lecturas actuales (`contadores={'hobbs': 1204.6, 'tach': …}`):
    son el punto de partida, y las operaciones suman desde ahí."""
    m = core_flota.modelo_activo(con, modelo)
    if m and m["es_plantilla"]:
        modelo = core_flota.asegurar_modelo_propio(con, modelo)
        m = core_flota.modelo_activo(con, modelo)
    tipo = tipo_activo or (m["tipo_activo"] if m else "dron")
    cur = con.execute(
        "INSERT INTO equipos(nombre, modelo, numero_serie, nota, tipo_activo, matricula, anio, base, fabricante, "
        "                    fecha_alta) VALUES(?,?,?,?,?,?,?,?,?, COALESCE(?, to_char(CURRENT_DATE,'YYYY-MM-DD')))",
        (nombre, modelo, numero_serie, nota, tipo, matricula or None, anio or None, base or None,
         fabricante or (m["fabricante"] if m else None), fecha_alta),
    )
    equipo_id = cur.lastrowid
    lista = (m["contadores"] if m else None) or core_flota.contadores_de_tipo(tipo)
    core_flota.asegurar_contadores(con, equipo_id, tipo, contadores or {}, lista=lista)
    # Cada equipo arranca con los componentes de SU modelo: un T100 no tiene las piezas del T50.
    piezas = con.execute("SELECT id FROM catalogo_piezas WHERE modelo=?", (modelo,)).fetchall()
    for p in piezas:
        con.execute(
            "INSERT INTO componentes(equipo_id, pieza_id, uso_inicial, ciclos_inicial, fecha_instalado) "
            "VALUES(?,?,0,0,(SELECT fecha_alta FROM equipos WHERE id=?)) ON CONFLICT DO NOTHING",
            (equipo_id, p["id"], equipo_id),
        )
    core_flota.recalcular_equipo(con, equipo_id)
    con.commit()
    return equipo_id


def componentes_de_equipo(con, equipo_id):
    return con.execute(
        """SELECT c.id, c.horas_uso, c.fecha_instalado, c.fecha_ultimo_cambio,
                  p.id AS pieza_id, p.clave, p.modulo, p.nombre, p.vida_util_horas, p.nota, p.mesh
           FROM componentes c JOIN catalogo_piezas p ON p.id = c.pieza_id
           WHERE c.equipo_id=? ORDER BY p.modulo, p.nombre""",
        (equipo_id,),
    ).fetchall()


# Columnas de una operación además de equipo, fecha y horas. Las de avión y las de condiciones
# de aplicación son opcionales: un dron las deja vacías.
COLUMNAS_OPERACION = ("tiempo_total", "despegues", "hectareas", "producto", "litros", "piloto", "cliente",
                      "zona", "lote", "nota", "hobbs_ini", "hobbs_fin", "tach_ini", "tach_fin", "aterrizajes",
                      "arranques", "combustible_gal", "pista", "tiempo_traslado", "ha_programadas",
                      "temperatura", "humedad", "viento", "velocidad", "altura", "dosis_objetivo",
                      # Libro de a bordo (RAC 91.1410) y libro de vuelo del UA (RAC 100.005).
                      "hora_salida", "hora_llegada", "origen", "destino", "proposito", "personal_id")


def registrar_operacion(con, equipo_id, horas_vuelo, fecha=None, commit=True, recalcular=True, **campos):
    """Anota la jornada y recalcula el uso de las piezas desde las operaciones.

    En un avión, si se dan Hobbs inicial y final y no las horas, las horas de vuelo son el
    avance del Hobbs (así los reportes de horas valen para toda la flota)."""
    if (horas_vuelo in (None, "", 0)) and campos.get("hobbs_fin") is not None and campos.get("hobbs_ini") is not None:
        horas_vuelo = round(float(campos["hobbs_fin"]) - float(campos["hobbs_ini"]), 2)
    valores = [campos.get(c) for c in COLUMNAS_OPERACION]
    cur = con.execute(
        f"INSERT INTO operaciones(equipo_id, fecha, horas_vuelo, {', '.join(COLUMNAS_OPERACION)}) "
        f"VALUES(?, COALESCE(?, date('now')), ?, {', '.join('?' * len(COLUMNAS_OPERACION))})",
        (equipo_id, fecha, horas_vuelo, *valores),
    )
    if recalcular:
        core_flota.recalcular_equipo(con, equipo_id)
    if commit:
        con.commit()
    return cur.lastrowid


def eliminar_operacion(con, operacion_id):
    """Borra la jornada y recalcula: sólo cambia el uso de las piezas que la volaron."""
    fila = con.execute("SELECT equipo_id FROM operaciones WHERE id=?", (operacion_id,)).fetchone()
    if not fila:
        return False
    con.execute("DELETE FROM operaciones WHERE id=?", (operacion_id,))
    core_flota.recalcular_equipo(con, fila["equipo_id"])
    con.commit()
    return True


# Por qué se tocó la pieza. «daño» es el caso que no depende de las horas: la pieza se rompe
# con la vida útil a medias y se cambia igual, y el contador arranca de cero como cualquier
# repuesto nuevo.
MOTIVOS = {"desgaste": "Desgaste / vida útil", "daño": "Daño o rotura",
           "preventivo": "Preventivo", "inspeccion": "Inspección", "otro": "Otro"}


def registrar_mantenimiento(con, equipo_id, componente_id, tipo, descripcion, costo, realizado_por,
                            fecha=None, motivo=None, orden_id=None, orden_codigo=None,
                            codigo_pieza=None, nombre_pieza=None, commit=True,
                            costo_repuesto=None, costo_mano_obra=None, firmado_por=None, licencia_firma=None,
                            reiniciar=True):
    """Anota la reparación en la bitácora y, si hubo cambio de pieza, la pone a cero DESDE LA
    FECHA DEL CAMBIO (antes se ponía a cero con fecha de hoy aunque el cambio fuera de otro día).

    Las horas que llevaba la pieza se calculan a esa fecha y se guardan: es el dato que dice si
    el cambio llegó por desgaste o adelantado por un daño. También se guarda cómo estaba el
    componente antes, para poder deshacer el cambio si el registro se borra.
    `costo` es el total; si llegan repuesto y mano de obra por separado, el total es su suma.
    """
    fecha = fecha or date.today().isoformat()
    if costo in (None, "") and (costo_repuesto is not None or costo_mano_obra is not None):
        costo = (costo_repuesto or 0) + (costo_mano_obra or 0)
    fila_eq = con.execute("SELECT horas_totales FROM equipos WHERE id=?", (equipo_id,)).fetchone()
    horas_actual = fila_eq["horas_totales"] if fila_eq else None
    pieza_id, horas_pieza = None, None
    antes = None
    if componente_id:
        comp = con.execute("SELECT pieza_id, horas_uso, uso_inicial, ciclos_inicial, fecha_ultimo_cambio, "
                           "fecha_instalado, pieza_serie_id FROM componentes WHERE id=?", (componente_id,)).fetchone()
        if comp:
            pieza_id = comp["pieza_id"]
            horas_pieza = core_flota.uso_hasta(con, componente_id, fecha)
            antes = comp
    cur = con.execute(
        "INSERT INTO mantenimientos(equipo_id, componente_id, tipo, fecha, horas_al_momento, descripcion, "
        "                           costo, realizado_por, pieza_id, horas_pieza, motivo, codigo_pieza, "
        "                           nombre_pieza, orden_id, orden_codigo, costo_repuesto, costo_mano_obra, "
        "                           firmado_por, licencia_firma, fecha_cambio_anterior, uso_inicial_anterior, "
        "                           ciclos_inicial_anterior, pieza_serie_id) "
        "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (equipo_id, componente_id, tipo, fecha, horas_actual, descripcion, costo, realizado_por,
         pieza_id, horas_pieza, motivo or ("desgaste" if componente_id else "otro"),
         codigo_pieza, nombre_pieza, orden_id, orden_codigo, costo_repuesto, costo_mano_obra,
         firmado_por, licencia_firma,
         (antes["fecha_ultimo_cambio"] or antes["fecha_instalado"]) if antes else None,
         antes["uso_inicial"] if antes else None, antes["ciclos_inicial"] if antes else None,
         antes["pieza_serie_id"] if antes else None),
    )
    if componente_id and antes and reiniciar:
        con.execute("UPDATE componentes SET uso_inicial=0, ciclos_inicial=0, fecha_ultimo_cambio=? WHERE id=?",
                    (fecha, componente_id))
        core_flota.recalcular_equipo(con, equipo_id)
    if commit:
        con.commit()
    return cur.lastrowid


def eliminar_mantenimiento(con, mantenimiento_id, usuario=None):
    """Borra un registro de la bitácora. Si ese registro fue el último cambio de la pieza, la
    pieza vuelve a como estaba antes (antes quedaba en cero horas aunque el cambio se anulara)."""
    m = con.execute("SELECT * FROM mantenimientos WHERE id=?", (mantenimiento_id,)).fetchone()
    if not m:
        return False
    if m["componente_id"] and m["uso_inicial_anterior"] is not None:
        comp = con.execute("SELECT fecha_ultimo_cambio FROM componentes WHERE id=?", (m["componente_id"],)).fetchone()
        otro_posterior = con.execute(
            "SELECT 1 FROM mantenimientos WHERE componente_id=? AND id<>? AND (fecha > ? OR (fecha = ? AND id > ?))",
            (m["componente_id"], m["id"], m["fecha"], m["fecha"], m["id"])).fetchone()
        if comp and comp["fecha_ultimo_cambio"] == m["fecha"] and not otro_posterior:
            con.execute("UPDATE componentes SET uso_inicial=?, ciclos_inicial=?, fecha_ultimo_cambio=? WHERE id=?",
                        (m["uso_inicial_anterior"], m["ciclos_inicial_anterior"] or 0,
                         m["fecha_cambio_anterior"], m["componente_id"]))
            # Si el anterior era la fecha de instalación, no hubo cambio previo.
            con.execute("UPDATE componentes SET fecha_ultimo_cambio=NULL WHERE id=? AND fecha_ultimo_cambio=fecha_instalado",
                        (m["componente_id"],))
    core_flota.auditar(con, "mantenimientos", mantenimiento_id, "eliminado", m["descripcion"] or m["nombre_pieza"],
                       None, usuario, "Registro de bitácora borrado")
    con.execute("DELETE FROM mantenimientos WHERE id=?", (mantenimiento_id,))
    core_flota.recalcular_equipo(con, m["equipo_id"])
    con.commit()
    return True


# ---------- Buscador de piezas del catálogo ----------

def _normalizar(texto):
    """Sin tildes y en minúsculas: «hélice» y «helice» tienen que encontrar lo mismo."""
    import unicodedata
    sin_tildes = unicodedata.normalize("NFD", str(texto or ""))
    return "".join(c for c in sin_tildes if unicodedata.category(c) != "Mn").lower()


# Cómo llama el técnico a las piezas frente a cómo las llama el listado DJI. Cada entrada es
# «lo que se teclea» -> otras formas que también valen. El listado oficial dice «válvula
# solenoide», pero en campo nadie la pide así: la pide como electroválvula.
SINONIMOS = {
    "electrovalvula": ["solenoide", "electrovalvula"],
    "electro": ["solenoide", "electro"],
    "solenoide": ["solenoide", "electrovalvula"],
    "antirretorno": ["antirretorno", "one-way", "one way", "unidireccional", "retencion"],
    "unidireccional": ["antirretorno", "one-way"],
    "check": ["antirretorno", "one-way"],
    "torica": ["torica", "o-ring", "o ring"],
    "oring": ["torica", "o-ring", "o ring"],
    "junta": ["junta", "empaque", "sellado", "gasket", "seal"],
    "empaque": ["empaque", "junta", "sellado", "gasket"],
    "sello": ["sellado", "seal", "reten", "empaque"],
    "reten": ["reten", "seal", "sellado"],
    "tapa": ["tapa", "cubierta", "cap", "cover", "tapon"],
    "tapon": ["tapon", "plug", "stopper", "tapa"],
    "cubierta": ["cubierta", "cover", "tapa", "carcasa"],
    "carcasa": ["carcasa", "shell", "housing", "alojamiento"],
    "manguera": ["manguera", "hose", "tubo", "tube"],
    "tubo": ["tubo", "tube", "manguera"],
    "abrazadera": ["abrazadera", "clamp", "clip"],
    "muelle": ["muelle", "resorte", "spring"],
    "resorte": ["resorte", "muelle", "spring"],
    "perno": ["perno", "tornillo", "bolt", "screw"],
    "tornillo": ["tornillo", "screw", "perno", "bolt"],
    "arandela": ["arandela", "washer"],
    "tuerca": ["tuerca", "nut"],
    "rodamiento": ["rodamiento", "bearing", "balinera"],
    "balinera": ["rodamiento", "bearing"],
    "helice": ["helice", "propeller", "pala", "blade"],
    "pala": ["pala", "blade", "helice"],
    "boquilla": ["boquilla", "nozzle"],
    "aspersor": ["aspersor", "sprinkler", "lanza", "centrifug"],
    "lanza": ["lanza", "lance", "aspersor"],
    "deposito": ["deposito", "tanque", "tank"],
    "tanque": ["tanque", "tank", "deposito"],
    "caudalimetro": ["caudalimetro", "flowmeter", "caudal", "flow"],
    "disipador": ["disipador", "heat sink", "radiador", "sink"],
    "radiador": ["radiador", "disipador", "heat sink"],
    "ventilador": ["ventilador", "fan"],
    "iman": ["iman", "magnet"],
    "placa": ["placa", "board", "pcb", "panel"],
    "cable": ["cable", "wire", "harness", "cableado"],
    "cableado": ["cableado", "cable", "harness", "wire"],
    "bateria": ["bateria", "battery"],
    "cargador": ["cargador", "charger"],
    "antena": ["antena", "antenna"],
    "camara": ["camara", "camera"],
    "lente": ["lente", "lens"],
    "luz": ["luz", "light", "led", "faro", "baliza"],
    "faro": ["faro", "light", "luz"],
    "tren": ["tren", "landing gear", "pata", "aterrizaje"],
    "pata": ["pata", "tren", "landing gear"],
    "brazo": ["brazo", "arm"],
    "marco": ["marco", "frame", "bastidor"],
    "bastidor": ["marco", "frame"],
    "bomba": ["bomba", "pump", "impulsor", "impeller"],
    "impulsor": ["impulsor", "impeller", "bomba"],
    "sensor": ["sensor", "sensing", "detector"],
    "filtro": ["filtro", "filter"],
    "conector": ["conector", "connector", "racor", "enchufe"],
    "racor": ["racor", "fitting", "conector"],
    "goma": ["goma", "rubber", "caucho", "silicona"],
    "caucho": ["goma", "rubber"],
    "anillo": ["anillo", "ring"],
    "correa": ["correa", "strap", "banda"],
    "adhesivo": ["adhesivo", "sticker", "glue", "pegatina"],
    "etiqueta": ["etiqueta", "label", "adhesivo"],
    "rejilla": ["rejilla", "grating", "grid", "parrilla"],
}


def _variantes(token):
    """Formas alternativas de un término de búsqueda, incluida la propia."""
    formas = SINONIMOS.get(token)
    if formas:
        return [_normalizar(f) for f in formas]
    # Sin sinónimo propio, se prueba también sin la «s» final: «tornillos» -> «tornillo».
    if len(token) > 3 and token.endswith("s") and SINONIMOS.get(token[:-1]):
        return [_normalizar(f) for f in SINONIMOS[token[:-1]]]
    return [token]


def buscar_piezas(con, equipo_id, texto, limite=25, incluir_despiece=True):
    """Busca en TODO lo que se puede cambiar de un dron, en dos catálogos a la vez:

    - `seguimiento`: las piezas con vida útil (catalogo_piezas). Traen el componente concreto de
      ese dron, sus horas y su nivel de desgaste; cambiarlas reinicia el contador.
    - `despiece`: el despiece completo de los diagramas DJI (catalogo_despiece). Traen código de
      pieza y módulo, pero DJI no les da vida útil, así que no hay contador que reiniciar; se
      apuntan en la bitácora con su código y, si hace falta, se elige a mano qué pieza con horas
      del mismo módulo se reinicia.

    Se busca por nombre (castellano e inglés), módulo, clave y código, sin tildes y por trozos:
    «emp hel» encuentra «Empaque de hélice» y «l00870» encuentra el tornillo por su código.
    """
    from core import alertas as core_alertas
    # Cada término se expande a sus sinónimos: basta con que UNA de las formas aparezca.
    consulta = [_variantes(t) for t in _normalizar(texto).split()]
    def casa(*campos):
        heno = _normalizar(" ".join(str(c or "") for c in campos))
        return all(any(f in heno for f in formas) for formas in consulta)

    seguimiento = []
    for c in core_alertas.componentes_con_estado(con, equipo_id):
        # Se busca también por la familia funcional: quien teclea «propulsión» sigue encontrando
        # las hélices aunque la etiqueta que se muestre sea ya la zona.
        if consulta and not casa(c["nombre"], c["zona"], c["modulo"], c["clave"]):
            continue
        seguimiento.append({
            "tipo": "seguimiento",
            "componente_id": c["id"], "equipo_id": c["equipo_id"], "pieza_id": c["pieza_id"],
            "clave": c["clave"], "codigo": None, "nombre": c["nombre"],
            "modulo": c["zona"] or c["modulo"], "familia": c["modulo"],
            "modulo_clave": None, "nombre_en": None,
            "vida_util_horas": c["vida_util_horas"], "horas_uso": c["horas_uso"],
            "vida_util_meses": c["vida_util_meses"], "meses_en_servicio": c["meses_en_servicio"],
            "meses_restantes": c["meses_restantes"], "sin_plazo": c["sin_plazo"],
            "restante": c["restante"], "pct": c["pct"], "nivel": c["nivel"], "nota": c["nota"],
            "fecha_ultimo_cambio": c["fecha_ultimo_cambio"], "piezas_modulo": [],
        })
    # Lo más gastado primero: si alguien escribe «motor» normalmente busca el que toca cambiar.
    seguimiento.sort(key=lambda d: (-d["pct"], _normalizar(d["nombre"])))
    if not incluir_despiece:
        return seguimiento[:limite]

    # Qué piezas con horas cuelgan de cada módulo del despiece, ya resueltas al componente de
    # este dron: es lo que se ofrece para reiniciar cuando se cambia un recambio suelto.
    modelo = modelo_de_laminas(con, modelo_de_equipo(con, equipo_id))
    por_modulo = piezas_catalogo_por_modulo(modelo)
    comps = {c["clave"]: c for c in core_alertas.componentes_con_estado(con, equipo_id)}
    def piezas_del_modulo(modulo_clave):
        salida = []
        for clave in por_modulo.get(modulo_clave, []):
            c = comps.get(clave)
            if c:
                salida.append({"componente_id": c["id"], "nombre": c["nombre"], "clave": c["clave"],
                               "modulo": c["zona"] or c["modulo"],
                               "horas_uso": c["horas_uso"], "vida_util_horas": c["vida_util_horas"],
                               "vida_util_meses": c["vida_util_meses"],
                               "meses_en_servicio": c["meses_en_servicio"],
                               "meses_restantes": c["meses_restantes"], "pct": c["pct"],
                               "nivel": c["nivel"]})
        return salida

    despiece = []
    for f in con.execute("SELECT * FROM catalogo_despiece WHERE modelo=? ORDER BY modulo, n",
                         (modelo,)).fetchall():
        if consulta and not casa(f["nombre"], f["nombre_en"], f["zona"], f["modulo"], f["codigo"]):
            continue
        despiece.append({
            "tipo": "despiece",
            "componente_id": None, "equipo_id": equipo_id, "pieza_id": None,
            "clave": None, "codigo": f["codigo"], "nombre": f["nombre"],
            "modulo": f["zona"] or f["modulo"], "lamina": f["modulo"],
            "modulo_clave": f["modulo_clave"], "nombre_en": f["nombre_en"], "n": f["n"],
            "auxiliar": bool(f["auxiliar"]),
            "vida_util_horas": None, "horas_uso": None, "restante": None, "pct": None,
            "vida_util_meses": None, "meses_en_servicio": None, "meses_restantes": None,
            "sin_plazo": True, "nivel": None, "nota": None, "fecha_ultimo_cambio": None,
            "piezas_modulo": piezas_del_modulo(f["modulo_clave"]),
        })
    # Las principales antes que la tornillería auxiliar, y dentro de cada grupo por nombre.
    despiece.sort(key=lambda d: (d["auxiliar"], _normalizar(d["modulo"]), _normalizar(d["nombre"])))

    # Las piezas con horas van primero: son las que el mantenimiento mira todos los días.
    return (seguimiento + despiece)[:limite]


def modelo_de_laminas(con, modelo):
    """Modelo cuyas láminas y despiece valen para `modelo`: el propio, o la plantilla de la que
    sale (el Cessna de una empresa es una copia de la plantilla C188A y usa su catálogo)."""
    fila = con.execute("SELECT plantilla FROM modelos_activo WHERE clave=?", (modelo,)).fetchone()
    return core_modelos.con_laminas(modelo, fila["plantilla"] if fila else None) or modelo


def modelo_de_equipo(con, equipo_id):
    """Modelo de un equipo (dron o avión). Sin equipo concreto manda el predeterminado."""
    if equipo_id:
        fila = con.execute("SELECT modelo FROM equipos WHERE id=?", (equipo_id,)).fetchone()
        if fila and fila["modelo"]:
            return fila["modelo"]
    return core_modelos.PREDETERMINADO


def contar_piezas(con, modelo=None):
    """Cuántas piezas hay en cada catálogo. Lo usa la interfaz para decirlo en el buscador."""
    filtro, params = ("WHERE modelo=?", (modelo,)) if modelo else ("", ())
    uno = lambda sql: con.execute(sql, params).fetchone()["n"]
    return {
        "modelo": modelo,
        "seguimiento": uno(f"SELECT COUNT(*) n FROM catalogo_piezas {filtro}"),
        "despiece": uno(f"SELECT COUNT(*) n FROM catalogo_despiece {filtro}"),
        "modulos": uno(f"SELECT COUNT(DISTINCT modulo_clave) n FROM catalogo_despiece {filtro}"),
    }


# ---------- Bitácora de reparaciones ----------

def bitacora(con, equipo_id=None, desde=None, hasta=None, motivo=None, solo_piezas=False, limite=500):
    """Historial de reparaciones, una fila por intervención, con la pieza y sus horas al cambiar."""
    cond, params = ["1=1"], []
    if equipo_id:
        cond.append("m.equipo_id=?"); params.append(equipo_id)
    if desde:
        cond.append("m.fecha >= ?"); params.append(desde)
    if hasta:
        cond.append("m.fecha <= ?"); params.append(hasta)
    if motivo:
        cond.append("COALESCE(m.motivo,'desgaste') = ?"); params.append(motivo)
    if solo_piezas:
        cond.append("m.pieza_id IS NOT NULL")
    params.append(limite)
    filas = con.execute(
        f"""SELECT m.*, e.nombre AS equipo, e.modelo,
                   COALESCE(p.nombre, pc.nombre, m.nombre_pieza) AS pieza,
                   COALESCE(p.zona, pc.zona,
                            (SELECT cd.zona FROM catalogo_despiece cd WHERE cd.codigo = m.codigo_pieza LIMIT 1),
                            p.modulo, pc.modulo) AS modulo,
                   COALESCE(p.vida_util_horas, pc.vida_util_horas) AS vida_util_horas
            FROM mantenimientos m
            JOIN equipos e ON e.id = m.equipo_id
            LEFT JOIN catalogo_piezas p ON p.id = m.pieza_id
            LEFT JOIN componentes c ON c.id = m.componente_id
            LEFT JOIN catalogo_piezas pc ON pc.id = c.pieza_id
            WHERE {' AND '.join(cond)}
            ORDER BY m.fecha DESC, m.id DESC LIMIT ?""", params).fetchall()
    salida = []
    for f in filas:
        d = dict(f)
        d["motivo"] = d.get("motivo") or ("desgaste" if d.get("pieza_id") else "otro")
        d["motivo_txt"] = MOTIVOS.get(d["motivo"], d["motivo"])
        vida = d.get("vida_util_horas") or 0
        horas = d.get("horas_pieza")
        # Adelantado = la pieza se cambió sin haber consumido ni el 75 % de su vida útil.
        d["pct_vida"] = round(horas / vida * 100, 1) if vida and horas is not None else None
        d["adelantado"] = bool(d["pct_vida"] is not None and d["pct_vida"] < 75)
        salida.append(d)
    return salida


def resumen_bitacora(con, equipo_id=None):
    filas = bitacora(con, equipo_id, limite=10 ** 6)
    piezas = [f for f in filas if f["pieza_id"]]
    return {
        "total": len(filas),
        "piezas_cambiadas": len(piezas),
        "por_dano": sum(1 for f in filas if f["motivo"] == "daño"),
        "adelantados": sum(1 for f in piezas if f["adelantado"]),
        "costo": round(sum(f["costo"] or 0 for f in filas), 2),
    }


# ---------- Operaciones: edición y recálculo de horas ----------

CAMPOS_OPERACION = ("fecha", "horas_vuelo", "tiempo_total", "despegues", "hectareas",
                    "producto", "litros", "piloto", "cliente", "zona", "lote", "nota",
                    "hobbs_ini", "hobbs_fin", "tach_ini", "tach_fin", "aterrizajes", "arranques",
                    "combustible_gal", "pista", "tiempo_traslado", "ha_programadas",
                    "temperatura", "humedad", "viento", "velocidad", "altura", "dosis_objetivo",
                    "hora_salida", "hora_llegada", "origen", "destino", "proposito", "personal_id")
_NUMERICOS_OP = {"horas_vuelo", "tiempo_total", "hectareas", "litros", "hobbs_ini", "hobbs_fin", "tach_ini",
                 "tach_fin", "combustible_gal", "tiempo_traslado", "ha_programadas", "temperatura",
                 "humedad", "viento", "velocidad", "altura", "dosis_objetivo"}
_ENTEROS_OP = {"despegues", "aterrizajes", "arranques", "personal_id"}


def _valor_operacion(campo, valor):
    """Normaliza un valor recibido del formulario/Excel al tipo de la columna."""
    if valor in (None, ""):
        return 0.0 if campo == "horas_vuelo" else None
    if campo in _NUMERICOS_OP:
        return float(str(valor).replace(",", "."))
    if campo in _ENTEROS_OP:
        return int(float(str(valor).replace(",", ".")))
    return str(valor).strip() or None


# Rangos válidos de una operación. Fuera de estos valores casi siempre es un error de digitación
# (una temperatura de 92 °C, un viento de 200 km/h): se rechaza con un mensaje claro.
RANGOS_OPERACION = {
    "horas_vuelo": (0, 24, "h"), "tiempo_total": (0, 24, "h"), "tiempo_traslado": (0, 24, "h"),
    "hectareas": (0, 3000, "ha"), "ha_programadas": (0, 3000, "ha"), "litros": (0, 200000, "L"),
    "despegues": (0, 500, ""), "aterrizajes": (0, 300, ""), "arranques": (0, 300, ""),
    "combustible_gal": (0, 500, "gal"), "temperatura": (-5, 55, "°C"), "humedad": (0, 100, "%"),
    "viento": (0, 80, "km/h"), "velocidad": (0, 80, "m/s"), "altura": (0, 300, "m"),
    "dosis_objetivo": (0.3, 200, "L/ha"),
}
NOMBRES_CAMPO = {"horas_vuelo": "horas de vuelo", "tiempo_total": "tiempo total", "tiempo_traslado": "traslado",
                 "ha_programadas": "ha programadas", "combustible_gal": "combustible", "dosis_objetivo": "dosis objetivo"}


def validar_operacion(campos, previa=None):
    """Lista de errores (vacía si todo está bien). `campos` son los valores nuevos ya numéricos;
    `previa`, la operación guardada (para comprobar coherencia al editar un solo campo)."""
    errores = []
    for c, (lo, hi, u) in RANGOS_OPERACION.items():
        v = campos.get(c)
        if v is None or v == "":
            continue
        try:
            v = float(str(v).replace(",", "."))
        except ValueError:
            errores.append(f"{NOMBRES_CAMPO.get(c, c)}: no es un número"); continue
        if v < lo or v > hi:
            errores.append(f"{NOMBRES_CAMPO.get(c, c).capitalize()} fuera de rango ({v:g} {u}; válido {lo:g}–{hi:g})".replace(" )", ")"))
    todo = dict(previa or {}); todo.update({k: v for k, v in campos.items() if v not in (None, "")})
    def n(k):
        try:
            return float(str(todo.get(k)).replace(",", ".")) if todo.get(k) not in (None, "") else None
        except ValueError:
            return None
    if n("horas_vuelo") is not None and n("tiempo_total") is not None and n("horas_vuelo") > n("tiempo_total") + 0.05 \
            and ("horas_vuelo" in campos or "tiempo_total" in campos):
        errores.append("Las horas de vuelo no pueden superar el tiempo total de la jornada")
    for a, b in (("hobbs_ini", "hobbs_fin"), ("tach_ini", "tach_fin")):
        if n(a) is not None and n(b) is not None and n(b) < n(a) and (a in campos or b in campos):
            errores.append(f"La lectura final de {a.split('_')[0].title()} es menor que la inicial")
    f = campos.get("fecha")
    if f and str(f)[:10] > date.today().isoformat():
        errores.append("La fecha de la operación no puede ser futura")
    return errores


def actualizar_operacion(con, operacion_id, cambios, commit=True, recalcular=True):
    """Guarda cambios de una operación y recalcula el uso de las piezas del equipo.

    Antes la diferencia de horas se aplicaba a TODAS las piezas del equipo, incluidas las que se
    montaron después de esa operación. Ahora el uso sale de las operaciones de cada pieza."""
    fila = con.execute("SELECT * FROM operaciones WHERE id=?", (operacion_id,)).fetchone()
    if not fila:
        return None
    campos, valores = [], []
    for campo in CAMPOS_OPERACION:
        if campo in cambios:
            campos.append(f"{campo}=?")
            valores.append(_valor_operacion(campo, cambios[campo]))
    if not campos:
        return dict(fila)
    valores.append(operacion_id)
    con.execute(f"UPDATE operaciones SET {', '.join(campos)} WHERE id=?", valores)
    if recalcular:
        core_flota.recalcular_equipo(con, fila["equipo_id"])
    if commit:
        con.commit()
    return dict(con.execute("SELECT * FROM operaciones WHERE id=?", (operacion_id,)).fetchone())


# ---------- Numeración de órdenes ----------

def siguiente_codigo(con, tabla, prefijo):
    """Devuelve un código correlativo por año, p. ej. OT-2026-014."""
    from datetime import date
    anio = date.today().year
    patron = f"{prefijo}-{anio}-%"
    fila = con.execute(f"SELECT codigo FROM {tabla} WHERE codigo LIKE ? ORDER BY codigo DESC LIMIT 1", (patron,)).fetchone()
    n = int(fila["codigo"].rsplit("-", 1)[1]) + 1 if fila else 1
    return f"{prefijo}-{anio}-{n:03d}"


# ---------- Personal ----------

# Qué es cada contacto para la app. Los tres primeros reciben órdenes; los demás son agenda.
ROLES = {
    "piloto": "Piloto",
    "tecnico": "Técnico de mantenimiento",
    "admin": "Administrador",
    "operario": "Operario de campo",
    "cliente": "Cliente",
    "proveedor": "Proveedor",
    "servicio": "Servicio técnico externo",
    "otro": "Otro",
}
# Roles a los que se les asigna trabajo: son los que aparecen en los desplegables de las órdenes.
ROLES_OPERATIVOS = ("piloto", "tecnico", "admin", "operario")

CAMPOS_PERSONA = ("nombre", "rol", "cargo", "empresa", "documento", "email", "telefono",
                  "telefono2", "direccion", "ciudad", "licencia", "licencia_vence", "ingreso",
                  "activo", "nota")


def contactos(con, rol=None, incluir_inactivos=True):
    """Directorio completo, con el trabajo que tiene cada uno a cuestas."""
    cond, params = ["1=1"], []
    if rol:
        cond.append("p.rol=?"); params.append(rol)
    if not incluir_inactivos:
        cond.append("p.activo=1")
    # Los contadores se calculan UNA vez por tabla (agrupados por nombre) y se cruzan con el
    # directorio: con seis subconsultas correlacionadas por persona, 300 contactos sobre
    # 100.000 operaciones tardaban 9 segundos; así tarda decenas de milisegundos.
    filas = con.execute(
        f"""SELECT p.*,
                   COALESCE(ot.abiertas, 0) ot_abiertas, COALESCE(ot.total, 0) ot_total,
                   COALESCE(os.abiertas, 0) os_abiertas, COALESCE(os.total, 0) os_total,
                   COALESCE(op.vuelos, 0) vuelos, COALESCE(op.horas, 0) horas_vuelo
            FROM personal p
            LEFT JOIN (SELECT asignado_a nombre, COUNT(*) total,
                              COUNT(*) FILTER (WHERE estado NOT IN ('completada','cancelada')) abiertas
                       FROM ordenes_trabajo GROUP BY asignado_a) ot ON ot.nombre = p.nombre
            LEFT JOIN (SELECT piloto nombre, COUNT(*) total,
                              COUNT(*) FILTER (WHERE estado NOT IN ('finalizada','cancelada')) abiertas
                       FROM ordenes_servicio GROUP BY piloto) os ON os.nombre = p.nombre
            LEFT JOIN (SELECT piloto nombre, COUNT(*) vuelos, SUM(horas_vuelo) horas
                       FROM operaciones GROUP BY piloto) op ON op.nombre = p.nombre
            WHERE {' AND '.join(cond)}
            ORDER BY p.activo DESC, p.nombre""", params).fetchall()
    salida = []
    for f in filas:
        d = dict(f)
        d["rol_txt"] = ROLES.get(d["rol"], d["rol"])
        d["horas_vuelo"] = round(d["horas_vuelo"] or 0, 1)
        d["operativo"] = d["rol"] in ROLES_OPERATIVOS
        d["licencia_vencida"] = bool(d.get("licencia_vence") and d["licencia_vence"] < _hoy())
        salida.append(d)
    return salida


def _hoy():
    from datetime import date
    return date.today().isoformat()


def resumen_contactos(con):
    lista = contactos(con)
    por_rol = {}
    for c in lista:
        por_rol[c["rol"]] = por_rol.get(c["rol"], 0) + 1
    return {
        "total": len(lista),
        "activos": sum(1 for c in lista if c["activo"]),
        "operativos": sum(1 for c in lista if c["operativo"] and c["activo"]),
        "sin_correo": sum(1 for c in lista if c["activo"] and not c["email"]),
        "licencias_vencidas": sum(1 for c in lista if c["licencia_vencida"]),
        "por_rol": por_rol,
        "roles": ROLES,
    }


def personal_activo(con, rol=None):
    filtro = "AND rol=?" if rol else ""
    params = (rol,) if rol else ()
    return [dict(f) for f in con.execute(
        f"SELECT * FROM personal WHERE activo=1 {filtro} ORDER BY nombre", params).fetchall()]
